#apiVersion: v1
#kind: Namespace
#metadata:
#  labels:
#   control-plane: controller-manager
# name: system
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-operator  
  labels:
    control-plane: flask-operator
spec:
  selector:
    matchLabels:
      control-plane: flask-operator
  replicas: 1
  template:
    metadata:
      labels:
        control-plane: flask-operator
    spec:
      serviceAccountName: flask-operator
      containers:
        - name: manager
          args:
            - "--enable-leader-election"
            - "--leader-election-id=flask-operator"
          env:
            - name: ANSIBLE_GATHERING
              value: explicit
            - name: OPERATOR_NAME
              value: "flask-operator"
            - name: RELATED_IMAGE_FLASK
              value: quay.io/rhm_samples/flask-server:v0.0.1
            - name: RELATED_IMAGE_VUE
              value: quay.io/rhm_samples/flask-vue-client:v0.0.1
          image: quay.io/ritushreepurkait/flask-operator-ansible:v0.0.1
      terminationGracePeriodSeconds: 10
