# permissions for end users to view flasks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: flask-viewer-role
rules:
- apiGroups:
  - example.com
  resources:
  - flasks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - example.com
  resources:
  - flasks/status
  verbs:
  - get
